-- phpMyAdmin SQL Dump
-- version 3.4.5
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 27, 2012 at 08:51 PM
-- Server version: 5.5.16
-- PHP Version: 5.3.8

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `web`
--

-- --------------------------------------------------------

--
-- Table structure for table `data`
--

CREATE TABLE IF NOT EXISTS `data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `desc` text NOT NULL,
  `rules` text NOT NULL,
  `timeline` text NOT NULL,
  `regusers` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=23 ;

--
-- Dumping data for table `data`
--

INSERT INTO `data` (`id`, `event_id`, `name`, `desc`, `rules`, `timeline`, `regusers`) VALUES
(1, 'akraman', 'Akraman', 'Infotsav-12 presents AKRAMAN-For all those who love to play off in the arena of hacking.\r\nThe contest would trigger off such hacking questions to vouch for the youth''s knack, which will battle in the arena of simmered potential threats. Come, accept the challenge and have fun HACKING.<b></br></br><li>Prize Money : Rs.6000</li></b>', '<li>Team size is utmost 2 members.</li>\r\n<li>The event will be held online as mentioned in the timeline.</li>\r\n<li>So, all the participants are requested to register on the Infotsav website http://www.infotsav.org for participation.</li>\r\n<li>The top two teams will be awarded the cash prize.</li>\r\n<li>Only students who are studying in graduate and post-graduate level in any University are eligible to take part.</li>\r\n<li>If any team(s) is found posting answers in any forum will be immediately disqualified without any prior notice.</li>\r\n<li>Any team found having fake information regarding qualification criteria or profile information shall be immediately disqualified.</li>\r\n<li>Any team which attempts to hack/deliberately crash the judging system will be immediately disqualified.</li>\r\n<li>The decision of the organizers in declaring the results will be final and will be binding to all. No queries in this regard will be entertained.</li>', '<ul><li>Online event to be held on 5th November 2012 from 00:00:00 to 23:59:59.</li></br> <li>The participants shortlisted after online event need to report at institute for the live event to be held on 10th November 2012.</li></ul>', 3),
(2, 'analyst', 'Analyst', '<ul><li>Analyst-The Case Study Event is all about\r\njudging your intellect, managerial skills and ability to craft sustainable solutions to\r\nproblems that organizations face today. If you can strain you nerve and sinew, and come\r\nup with solutions that are practical and implementable, Analyst has a place for you.\r\nChallenging live cases from some great ventures await your sight, who knows... may be\r\nyou can make a difference! Analyst this year comes with interesting cases, mindboggling\r\nreasoning and some big people to judge your acumen and innovation. Come\r\njoin those who wish to provide street-smart, real-time feasible solutions and to prove\r\nthemselves a true Analyst.</li>', '<ul><li>Team size: 4 members</li>\r\n<li>The winners will be announced on the basis of presentation and the final document submitted.</li></ul>\r\n', '<ul><h6>Preliminary Phase:</h6>\r\n<li>Case to be uploaded on : 25thSeptember,2012</li>\r\n<li>Deadline for submission : 15th October,2012</li>\r\n<li>Results of Preliminary Phase : 20th October2012</li>\r\n\r\n<h6>Final Phase:</h6>\r\n<li>Presentation on-campus : 9thNovember,2012</li>\r\n<li>Enclosure of Live-case : After completion of Presentation</li>\r\n<li>Dead-line for submission : 11th November,2012</li></ul>', 3),
(3, 'brouhaha', 'Brouhaha', '<ul><li>Brouhaha is the advertising contest that is\r\nheld under Infotsav. It is a noisy clamorous response to a stimulus, produced by a crowd. \r\nIt can also refer to the reaction expressed over a period of time to an event.</li><li>Advertising is a form of communication that\r\ntypically attempts to persuade potential customers to purchase or to consume more of a\r\nparticular brand of product or service. Advertisements are designed to generate increased\r\nconsumption of those products and services through the creation and reinforcement of\r\n"brand image" and "brand loyalty". Every major medium is used to deliver these\r\nmessages, including television, radio, cinema, magazines, newspapers, video games, the\r\nInternet and billboards.</li></ul>\r\n<ul class=''download''><li><a href=''downloads/brouhaha_case.pdf'' target=''_blank'' style=''none''>Round 1 case</a></li></ul>\r\n<ul><li>Prize Money : Rs.12,000</li></b>\r\n</ul>', '<ul><li>The maximum size of a team is three.</li>\r\n<li>The logos provided are to be used in every advertisement. </li>\r\n<li>Two print advertisements, one audio advertisement and one video advertisement(optional) should be submitted. </li>\r\n<li>While preparing the advertisement the use of the name of rival companies is prohibited.</li>\r\n<li>The print advertisements should be targeting newspapers and magazines. </li>\r\n<li>The video advertisement should not be more than 40 seconds and should be in .mpg, .avi or .flv format and flash presentation is also allowed.</li>\r\n<li>The audio advertisement should not be more than 20 seconds long and should be in .mp3 or .wmv format.</li>\r\n<li>Advertisements will be judged on the basis of their originality, design and tagline/caption used.</li>\r\n<li>Legality of the advertisements is foremost priority.  </li>\r\n<li>Presentation should be in ENGLISH only. The language HINDI is also allowed but can be used only in video and audio advertisement.</li>\r\n<li>The participants are required to send the soft copy of their entry to the mail id brouhaha@infotsav.org. A document providing the name of the team, members of the team, name of the institute, e-mail addresses and contact numbers is to be submitted along with the advertisements.</li></ul>', '<ul>\r\n<h6>Phase 1(online phase)</h6>\r\n<li>Case to be uploaded on : 6th October,2012</li>\r\n<li>Deadline for submission : 20th October,2012</li>\r\n<li>Results of Preliminary Phase : 23th October2012</li>\r\n<h6>Phase 2 (On-campus)</h6>\r\n<li>The participants shortlisted have to present their first phase product advertisement describing\r\nthem in detail.</li>\r\n<h6>Phase 3(On-campus)</h6>\r\n<li>The product for the third phase will be uploaded, after short listing the participants for second\r\nphase.</li>\r\n<li>The participants shortlisted for the second phase continue to the third phase and are to\r\npresent advertisements of next product describing them in detail.</li></ul>', 4),
(4, 'code_weavers', 'Code Weavers', '<ul><li>Do you have the brain of a genius? The online programming contest is here for you. Show your programming skills and provide\r\nthe best possible solution you can. After all life doesn''t give a second chance. So prove\r\nyourself on the battlefield and only then you will be a great warrior.</li>\r\n<li>Prize Money : Rs.9000</li></ul>', '<ul><li>Team size is at most 3 members.</li>\r\n<li>This mega event will be hosted at CODECHEF (A Directi Educational Initiative). </li>\r\n<li>So, all the participants are requested to register on the hosting website http://www.codechef.com prior to the commencement of the contest.</li>\r\n<li>Only students who are studying in graduate and post-graduate level in any Indian University are eligible to take part.</li>\r\n<li>Permitted languages to provide solution are C, C++ and Java.</li>\r\n<li>Compilers to be used: </li>\r\n<li>gcc (gcc (GCC) 4.1.2) for C </li>\r\n<li>g++ (g++ (GCC) 4.1.2) for C++ </li>\r\n<li>j2sdk1.5.0 (javac 1.5.0_10) for Java.</li>\r\n<li>Submission has to be done in a proper format on the host site (via file upload/embedded frame), failing which the entries shall not be accepted.</li>\r\n<li>If any team(s) is found to copy source code of other teams, that team will be immediately disqualified.</li>\r\n<li>Any team found having fake information regarding qualification criteria or profile information shall be immediately disqualified.</li>\r\n<li>Any team which attempts to hack/deliberately crash the judging system will be immediately disqualified.</li>\r\n<li>The decision of the organizers in declaring the results will be final and will be binding to all.</li></ul>\r\n', '<ul><li>On 7 Nov''2012</li></ul>', 3),
(5, 'cstrike', 'Counter Strike', '<ul><li>The battle of the virtual world has\r\n		begun. Are you game? This Infotsav 12 the world will be rocked by the cyber warriors.\r\n		Gamiacs is back with a bang. And this time it''s not only more competitive and tougher\r\n		but it has added an all new dimension in its already humungous artillery of\r\n		entertainment.This time round different games will be organized to bring out the\r\n		ultimate gamer who resides somewhere in you! So gear up, reload thy guns, sharpen you\r\n		knifes and prepare for the ultimate burnout. Counter-Strike is about as close as you will ever get to saving the world; or destroying it!\r\n		Now Counter-Strike will never be the same!</li>\r\n		<li>Prize Money: Rs 6000</li></ul>', '<ul><li>Competition Method: 5 vs. 5 (Team Play, 5 players per team).</li>\r\n<li>The first team to win 16 rounds is declared the winner.</li>\r\n<li>In the case of a 15-15 tie after regulation:\r\nThe match go for overtime. Overtime consists of 6 rounds with starting money of $10,000. Each team will play 3 rounds as Terrorist and 3 rounds as Counter-Terrorist. The team to win 4 rounds first, is declared the winner. In the case of another tie, the overtime will be repeated until a winner is declared.</li>\r\n<li>Official Maps: De_Dust2,De_Inferno,De_Nuke, De_Train </li>\r\n<li>Binding Duck to scroll wheel is not allowed.</li>\r\n<li>For more information, go through Downloads section</li></ul>', '<ul><li>9 Nov''12-11 Nov''12</li></ul>', 4),
(6, 'fifa', 'Fifa', '<ul><li>The world stands on the brink, and Makarov is intent on bringing civilization to its knees. \r\n		In this darkest hour you''re running across an unfamiliar planet while a horde of disgusting aliens chase you. \r\n		You blast them with a laser and escape to safety. The adrenaline rush of driving at breakneck speeds, the pressure of\r\nfierce competition, the fear of losing control, the intense concentration and athleticism needed to harness the power of speeding....\r\nthis is the awaited Gamiacs of Infotsav where the best in the country tackle to settle who is best in the gamble! \r\nThis year Infotsav promises you best technology, graphics and environment for gaming.</li>\r\n<li>Prize Money: Rs 1500</li></ul>', '<ul><li>Competition Method: 1 vs. 1.</li>\r\n<li>Game Mode: International and Club</li>\r\n<li>Player changes and strategy changes are limited to 3 times during the game. (The changes before the start of first and second half are not included in this count.) </li>\r\n<li>the players must kick-off with a backward pass at the beginning of each half and after every goal is scored.</li>\r\n<li>It is not allowed to score a goal from one''s own half of the field.</li>\r\n<li>For more information, go through Downloads section</li></ul>', 'To Be Uploaded Soon', 3),
(7, 'forex', 'Forex', '<ul><li>Forex is the simulation of by far the largest financial market in the world that includes trading between central banks, currency speculators, \r\n		multinational corporations, governments and other financial institutions. This game provides a platform where the players can convert virtual money from one \r\n		currency to another. The player who has the maximum assets wins. The Foreign Exchange market exists whenever one currency is traded for another. \r\n		It gives a real time experience of the "foreign exchange" provided with virtual money and real time data to get the invaluable hand on experience.</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>Only registered users at http://www.infotsav.org/ can participate.</li>\r\n<li>A participant can make his/her another account only if his earlier account is freezed. In case it is found that the participant has created more than one user id he/she shall be disqualified. In case of any discrepancy organizers decisions will be final.</li>\r\n<li>There is only one round.</li>\r\n<li>In this round the participants have to trade with the virtual amount of $ one lakh. </li>\r\n<li>In case of tie, the organizer''s decision will be final.</li>\r\n<li>Rank will be calculated after every hour.</li>\r\n<li>The top ten players (as according to the rank) will be scrutinized for any fraud or fake transactions. The Final Winners shall be then intimated through mail and a list will be put up on the website.</li></ul>\r\n', '<ul><li>From 31 Oct''2012 to 8 Nov'' 2012</li></ul>', 3),
(8, 'job_b', 'Job Bureau', '<ul><li>Get to use the world''s latest technologies and software.\r\nIt''s time for you to experience the professional serene and achieve what you desire and are really capable of.\r\nInfotsav gives you a chance to get placed before the actual campus drive in a virtual world where you learn to be an efficient project leader and a skilled coder. The simulation takes you into the flock of assignments where you move ahead by gaining experience and money. The game checks your skills at choosing the right project at the right time, a single wrong move could forestall your winning chances</li><li>Prize Money : Rs.6000</li><ul>', '<ul><li>To be uploaded soon</li></ul>', '<ul><li>From 2 Nov'' 2012 to 4 Nov'' 2012</li></ul>', 4),
(9, 'la_i', 'La Ingenious', '<ul><li>La Ingenious is the software contest under the umbrella of Infotsav 2012. It is one of the most accolades winning technical event of the festival providing a platform to judge the feasibility and usefulness of software. </li><li>The contest will cover a vast domain of software development leaving no stone unturned.</li>\r\n<li>\r\n"A thumping amount of INR 15,000 is waiting for you. Come and grab it all."</li></ul>\r\n', '<ul><h5>Common Rules: </h5>\r\n<li>Maximum Team size allowed: 2</li>\r\n<li>The event will take place in 2 phases. </li>\r\n<li>Teams are required to register at Infotsav 2012 website.</li>\r\n<li>Phase I: Send your software/app SRS and Screenshots to laingenious@infotsav.org.</li>\r\n<li>SRS should not exceed 5 pages, Send 5 to 10 screenshots along with it.</li>\r\n<li>Phase II: Will be conducted during Infotsav with the shortlisted entries from Phase I.</li>\r\n<li>The source code of the application will be taken just for judging originality and will be kept safely.</li>\r\n<li>You can also participate in Andrios and Desknet simultaneously.</li>\r\n<li>None of the participants can be the part of two teams in the same domain.</li>\r\n<li>None of the teams can present more than one software in the same domain. </li>\r\n</br>\r\n<h5>Rules for Desknet:</h5>\r\n<li>All technologies and platforms are allowed.</li>\r\n<li>We will provide computer systems for presentation but still you can bring your own laptops.</li>\r\n<li>You are free to build software to serve any purpose i.e. no predefined domain.</li>\r\n</br>\r\n<h5>Rules for Andrios:</h5>\r\n<li>All mobile application development technologies and platforms are allowed.</li>\r\n<li>Participants must bring their own mobile devices for presenting their applications.</li></ul>\r\n', '<ul><h5>Phase 1:</h5>\r\n<li>The participants are required to submit SRS and Screenshots of their application.</li>\r\n<li>Submission Deadline: 20 October, 2012</li>\r\n<li>Declaration of Shortlisted participants for Final Round: 25, October, 2012</li>\r\n<h5>\r\nPhase 2:</h5>\r\n<li>The participants have to present their final Software on 10th November at IIITM Gwalior.</li></ul>', 3),
(10, 'line_s', 'Line Sequentus', '<ul><li>The line sequentes will basically be an event for the beginners in which they will have to compete with their line following robots \r\n		in the given arena and beat their respective opponents in terms of speed and time limits. This basic robot has to follow the black line on the background, taking the right turns. \r\n		The follower has to complete the race without losing the line. Each team gets one chance, and the team which finishes the race accurately in the least time wins.\r\n</li><ul> ', 'To Be Uploaded Soon', 'To be Uploaded Soon', 3),
(11, 'nfs', 'NFS', '<ul></li>Hello all,There are really REALLY big prizes out there up for grabs. But they are all locked in a castle.\r\n		All you have to do is go there get them. You can just drive \r\n		right through the walls at full throttle in your fully upgraded Porsche and take it all!  We are talking about \r\n		the much awaited Infotsav Gaming Zone which promises to be biGGer and beTTer. So be ready for Ultimate Burnout.</li>\r\n		<li>Prize Money: Rs 1500</li></ul>', '<ul><li>Competition Method: 1 vs. 1 (knockout).</li>\r\n<li>The use of Porsche Carrera GT and BMW M3 and Lotus Elise are not allowed.</li>\r\n<li>Graphic settings such as motion blur cannot be set using external utilities. </li>\r\n<li>At the end of each match, players must maintain the final screens and receive confirmation from a referee.</li>\r\n<li>For more information, go through Downloads section</li></ul>', '<ul><li>9 Nov''12-11 Nov''12</li></ul>', 4),
(12, 'open_c', 'Open Challenge', '<ul><li>This event would be an open platform for all the budding engineers, scientists, and researchers who can come up with their innovative designs and implementations in the field of robotics and exhibit them in front of our elite panel and explain the working of their machines.\r\n		The participants would be judged on the basis of their innovation, implementation and demonstration.The contestants are to demonstrate a robot that performs interesting tasks for applications such \r\nas in entertainment, domestic chores, industry etc. \r\n</li></ul>', '<ul><li>The competing robots can start from any point in the contest arena. </li>\r\n<li> A total duration of up to 10mins is allocated for setting up the robot and any accessory equipment and demonstration of its capability. The time duration will be measured from the moment the contestants enter the arena. If more than 10 minutes elapsed, the robot must be removed from the arena.</li>\r\n<li>In the case where the contestants wish to employ radio control, they should inform the secretariat in advance. Contestants should not broadcast radio signals while another contestant''s robot is performing.</li>\r\n<li>In the case that a robot requires special accessory equipment or tools during its performance,the contestants will provide such items.</li>\r\n<li>In the case that a robot performance is to be accompanied by music, the contestants should provide the means to reproduce this music.</li>\r\n<li>There is no specific flooring material of the contest arena. The flooring will very much depend on the available contest site. However, if there is a special requirement such as carpet, the contestants will have to provide for it.</li>\r\n<li>One power point of 220/230V, 50 Hz supply will be made available. However, the teams are to provide their own power adapter and extension means if it is required.</li>\r\n<li>For air supply, the contestants are to provide their own air compressor units if necessary. </li>\r\n<li>The designs of the competing robots must be original and unique. No two identical designs are allowed in the competition.</li>\r\n<li>The expenses incurred in transportation and setup of equipment is to be borne by the individual teams.</li>\r\n<li>The boundary for the area will be black or white depending on the floor. </li>\r\n<li> Robots that can, in principle, compete in other should not be allowed to compete in the open category event.</li>\r\n</ul>', '<ul><li>To be uploaded soon</li></ul>', 4),
(13, 'pinnacle', 'Pinnacle', '<ul><li>If you have a unique idea that carves you out as a successful entrepreneur, then we\r\nwelcome you to the most appreciated event of Infotsav. It provides your idea, a platform\r\nand eventually a spark just sufficient to ignite you. So what are you waiting for? It''s show\r\ntime.\r\nPinnacle is the flagship event of Infotsav''12 which is being conducted from 09th to 11th\r\nNovember 2012. The event is attracting students from the best B-schools and Engineering\r\ncolleges around the country.</li>\r\n<h5>Prize Money</h5>\r\n<li>First Prize : Rs.15000</li>\r\n<li>Second Prize: Rs.10000</li>\r\n<li>The winning Business Plan will be mentored by Incubation Centre ABV-IIITM.</li></ul>\r\n', '<ul><li>There is no registration fee.</li> \r\n<li>Executive Summary and all other documents/queries to be sent to pinnacle@infotsav.org </li>\r\n<li>A team should comprise of a maximum of 4 members. </li>\r\n<li>Strictly adhere to the format mentioned. To view the format go to download section. </li>\r\n<li>Business plans on company/start up registered before 1st September, 2011 are not eligible to participate. Entries must contain the original work of participants. </li>\r\n<li>The decision of the judges and organizers will be final and binding to all the participants. </li>\r\n<li>Any of the terms and conditions can be changed by the organizers anytime ensuring to give the participants appropriate time to respond to the changes. </li>\r\n</br>\r\n<b>The B-plans will be evaluated based on following criteria''s:-</br></br>\r\n<li>The clarity and potential of the market opportunity. </li>\r\n<li>Innovativeness of business concept. </li>\r\n<li>Feasibility of the plan. </li>\r\n<li>The overall evaluation of potential reward to risk. </li>\r\n<li>Marketing Strategy. </li>\r\n<li>Financial Analysis. </li>\r\n<li>Sustainability and Scalability of Business Model. </li>\r\n<li>Quality of presentation.</li></b></ul>', '<ul>\r\n<li>1st phase: Executive summary Submission: 18th September - 8 October: Results on 12 October.</li>\r\n<li>2nd phase: Business Plan submission + Mentorship: 12th October to 20th October, results on 22nd October.</li>\r\n<li>3rd phase: Final presentation and a work shop at the campus.</li>\r\n</ul>', 3),
(14, 'rev_e', 'Reverse Engineering', '<ul><li>Infotsav 2012 presents Reverse Engineering,a competition to prove your fundamental understanding skills as an engineer. \r\nIt''s here to test your logical thinking along with systematic approach to analyze the pattern. You are given an executable program or an application and are asked to do reverse coding, that is develop the source code.</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>First Round -5th November 2012</li>\r\n<li>Second Round - 9th Novermber 2012</li>\r\n<li>Third Round - 10th November 2012</li></ul>', '<ul><li>Candidate will participate individually.</li>\r\n<li>Event will be conducted in 3 Rounds.</li>\r\n<li>First Round (Online Round) -This round will consist of 30 objective and 10 Subjective questions based on logical thinking and pattern recognition. Top 25 candidates of the first round will qualify for the second round. </li>\r\n<li>Second Round (On-Site Round) - In this round a set of 10 executable files will be provided to you along with the valid input range for those files. After analyzing the results produced by the executable file, candidates have to write a program that will produce same results. Allowed Languages - C, C++, Java and Python. Top 10 candidates from the second round will qualify for the final Round.</li>\r\n<li>Third Round (On-Site Round) -A software package and a website will be given to the candidates. They have to modify those packages as per the requirements given by us.</li<li>Candidate will participate individually.</li>\r\n<li>Event will be conducted in 3 Rounds.</li>\r\n<li>First Round (Online Round) -This round will consist of 30 objective and 10 Subjective questions based on logical thinking and pattern recognition. Top 25 candidates of the first round will qualify for the second round. </li>\r\n<li>Second Round (On-Site Round) - In this round a set of 10 executable files will be provided to you along with the valid input range for those files. After analyzing the results produced by the executable file, candidates have to write a program that will produce same results. Allowed Languages - C, C++, Java and Python. Top 10 candidates from the second round will qualify for the final Round.</li>\r\n<li>Third Round (On-Site Round) -A software package and a website will be given to the candidates. They have to modify those packages as per the requirements.</li></ul>\r\n', 3),
(15, 'robo_w', 'Robo Wars', '<ul><li>Robowars Mini is a real-time arcade game in which two opponents would be competing with their manually operated robots with the objective of immobilizing each other. \r\n		The last robot standing would be the winner.</li>\r\n<li>Name of Event: 	        RoboWars</li>\r\n<li>Robot per Event:		    Two</li>\r\n<li>Robot Weight Range:		4 Kgs</li>\r\n<li>Robot Dimensions:		    As per Rules</li>\r\n<li>Robot Control: 	        Autonomous or Remote-control</li>\r\n<li>Arena Specifications:		As per Center</li>\r\n<li>Engineering Principles:	Art, Mechanical Engineering, Electrical Engineering, Computer Science,etc.</li>\r\n</ul>', '<ul><li>Each team can have maximum of five members.</li>\r\n<li>During the match only two team-members will participate in competition, one member will control the bot and other to guide.</li>\r\n<b>Teams are allowed to switch members in different matches. </b>\r\n \r\n<li>Setup time: Team have be pre ready with their bots .No Time will be given after the bot is on the Arena.</li>\r\n<li>Match duration: 5 minutes.</li>\r\n<li>Winning criteria: Team can either win by direct knockout  or if the time runs out and there''s no knockout or both bots are inactive, the winner will be decided by the final points (Points are based on the creativity of the Bot , the team capability and the nof attacks made by the bot.)</li>\r\n \r\n<li>"A robot is declared immortal/victorious if its opponent becomes totally inactive. A robot will be declared inactive if it cannot display any movement for a time period of 30 seconds."</li>\r\n      \r\n<li> The matches will be direct knock out matches ,the winners keeps on moving ahead.</li></ul>', '<ul><li>To be uploaded soon</li></ul>', 3),
(16, 'robo_r', 'Robo Race', '<ul><li>Robo Race is a simple and entry level Robotics competition where couple of Robots would be competing with each other in terms of speed and accurate control.\r\n		There will be a race between two manually controlled robots. The robots should  be cotrolled via remote control. Each team gets only one chance and the team completing first wins the race.</li></ul>\r\n		', '<ul><li>Only one bot per team is allowed.</li>\r\n<li>Max no of people per team is 5.</li>\r\n<li>Robots must be manual. Both wired and wireless remotes are allowed.</li>\r\n<li>Onboard power supply should be present and it should not exceed 15V between any two points.</li>\r\n<li>There is no time limit for the compltion of the race.</li>\r\n<li>The robot which wanders off the arena shall be disqualified.</li></ul>', '<ul><li>To be uploaded soon</li></ul>', 4),
(17, 'robo_s', 'Robo Soccer', '<ul><li>Robo Soccer is a real time arcade game in which each bot is required to put a soccer ball in the desired area just like what happens in the game of football.</li>\r\n<li>Name of Event: 	        Robo Soccer</li>\r\n<li>Robot per Event:		    One</li>\r\n<li>Robot Weight Range:		5 Kgs</li>\r\n<li>Robot Dimensions:		    30*30*30 cms</li>\r\n<li>Battery Power:			40 V {230 V}	AC/Dc</li>\r\n<li>Arena Specifications:		As per Center</li>\r\n<li>Engineering Principles:	Art, Mechanical Engineering, Electrical Engineering, Computer Science,etc.</li></ul>', '<ul><h5>Game Procedure</h5>\r\n<li>Each team can have only 1 member.</li>\r\n<li>Team have be pre ready with their bots .No Time will be given after the bot is on the Arena.</li>\r\n<li>There will be different colours of ball and similar posts to them. The bots have to put the balls in the respective posts.</li>\r\n\r\n<b>Specifications</b>\r\n<li>The dimension of the bot should not exceed 30cm x 30cm x 30cm.</li>\r\n<li>The weight of the bot should not exceed 5 Kgs. (Excluding remote control and remote control wire.)</li>\r\n<li>In case of a wireless bot weight will be counted as (0.8x actual weight).</li>\r\n<li>Readymade gear boxes, parts, chassis, control circuits and remote \r\ncontrol can be used.</li>\r\n<b>Bot control:</b>\r\n<li>In case of wired bots, the wires should remain slack at any instant during the fight. All the wires coming out of the machine should be stacked as a single unit. Also, the wires should be projected 1000 mm above the ground to avoid entanglement.</li>\r\n<li>In case of wireless system, it should have a minimum four frequency \r\nremote control circuit or two dual control circuits or a transmitter receiver paired module so that the frequency interferences with opponent team can be avoided (in case of any interference in the wireless systems, they will not be considered for rematch or  in the results).</li>\r\n<li>Remote controls that are readily available in the market may also be used.</li>\r\n\r\n<b>Battery &amp; power:</b>\r\n<li>The machine can be  powered electrically only. </li>\r\n<li>Use of an IC engine in any form is not allowed. </li>\r\n<li>Batteries must be sealed, immobilized electrolyte types (such as gel cells, lithium, NiCad, NiMH, or dry cells).</li>\r\n<li>The electrical voltage at any point of time in the machine should not \r\nexceed 40 V DC/AC.</li>\r\n<li> 230V (AC) power will be provided.(wired bots).</li>\r\n<li>In case of wireless bot batteries should be placed on the bot also teams \r\ncannot use 230V(AC) external supply.</li>\r\n</ul>', '<ul><li>To be uploaded soon</li></ul>', 4),
(18, 'stock_s', 'Stock Sutra', '<ul><li>The game is a test of analyzing and\r\ndiagnosing powers of participants as some shares tumble and some soar at the stock\r\nmarket during the contest period. The participants are free to trade during market open\r\nand close hours. At the end of three weeks, the top 10 participants with the highest net\r\nworth are invited to institute campus to justify their choice of stocks.\r\nAn event in which the investment acumen of the contestants is tested where the\r\ncontestants have to invest in stocks and have to explain their investment strategy. In the\r\npresent accelerating growth period of the Indian economy, banks and other financial\r\ninstitutions are in acute need of good analytical minds for their investment decisions.</li>\r\n<li>Prize Money : Rs.6000</li></ul>', '<ul><li>Event will be played online for about 2 weeks.\r\n<li>The   participants   registering   are  provided   an  initial amount of Rs1,00,000  and  required  to  trade  in  stocks  from  the  NIFTY  index  and NIFTY</li>\r\n<li>JUNIOR index:- The game is a test of analyzing and diagnosing powers of participants as  some   shares  tumble   and   some   soar  at the  stock  market during</li>\r\n<li>The Contest period:- The  participants  are free to  trade  during market  open  and  close  hours.  At  the  end  of  the  contest,the  participant  with highest  net worth is thewinner.</li>\r\n<li>The decision of Judges and organizing team would be final and binding.</li>\r\n<li>The    Players  should   strictly  adhere   to deadlines   mentioned     in the  brochure. </li>\r\n<li>Players   are  requested    to  avail  accommodation      by  contacting   the hospitality team of Infotsav, 2012.</li>\r\n<li>Any     immediate     changes    in   the   deadlines    due   to   unforeseen circumstances would be communicated through our website-www.infotsav.org</li>\r\n</ul>', '<ul><li>From 31 Oct 2012-  8 Nov 2012</li></ul>', 3),
(19, 'trove_t', 'Trove Trace', '<ul><li>Does searching for a hidden treasure\r\nfascinate you? Are you enthralled by clues and puzzles and want to step into the shoes of\r\nthe master detective Holmes?? Then look no further, Trove Trace is where you should be.\r\nThere is nothing like a good riddle or a clue to spice up your hunt.\r\nAll the techno-freaks and pirates of the virtual world out there, trove trace is back - with\r\nmurkier corners, crazier questions, more twists and turns to blow your brains out, and a\r\nmonstrous amount of fun.\r\n</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>The event will be held online as mentioned in the timeline.</li>\r\n<li>So,all the participants are requested to register on the Infotsav website http://www.infotsav.org for participation. </li>\r\n<li>The top two participants will be awarded the cash prize.</li> \r\n<li>Only students who are studying in graduate and post-graduate level in any Indian University are eligible to take part.</li>\r\n<li>If anyone is found posting answers in any form will be immediately disqualified without any prior notice. </li>\r\n<li>Anyone found having fake information regarding qualification criteria or profile information shall be immediately disqualified.</li> \r\n<li>Anyone which attempts to hack/deliberately crash the judging system will be immediately disqualified.</li> \r\n<li>The decision of the organizers in declaring the results will be final and will be binding to all. No queries in this regard will be entertained.</li><ul>', '<ul><li>On 5 Nov'' 2012</li></ul>', 3),
(20, 'tycoon', 'Tycoon', '<ul><li>Are you outstanding from the crowd? But we\r\nneed here someone who can lead them. Competing increases you incrementally but\r\nCo-operating does it exponentially. The stage is set for you. "Come, participate with\r\nhundreds to stand against millions".Tycoon is the Best manager contest of Infotsav.\r\nIt is a quest to determine the person who is most knowledgeable of the who''s who of the\r\nbusiness fraternity. The contest is an individual one to make the competition more cut\r\nthroat and fierce. Add to it the elimination at each level, thus making the competition all\r\nthe more ruthless. But ultimately who so ever comes out as the winner gets to taste the\r\nforbidden fruit. He/She is accorded the title of the tycoon.</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>Round 1: Online quiz containing small puzzles and brief descriptive questions. Those qualified shall proceed to round 2.\r\n  OR\r\nOffline quiz for internal and on the spot participants.</li>\r\n<li>Round 2:\r\nGroup discussion: Shortlisted candidates participate in GD round and selected candidates proceed.</li>\r\n<li>Round 3:\r\nShort b-plan contest: Each finalist gets to present a b-plan in stipulated in time. </li></ul>', '<ul><li>To be uploaded soon</li></ul>', 3),
(21, 'web_m', 'Web Mania', '<ul><li>One of the finest way of expressing information in front of the world is\r\nthrough the web. It is the designing of these web pages that would attract many people to\r\nread the information.</br>With the event web mania we bring forward a chance for you\r\nto try your imagination and try your hands in the fascinating field of web designing. Try\r\nto be articulate in whatever you do .Do it fast and do it perfectly. Be a professional\r\ndesigner, know the psychology of color So, grab this opportunity with both your hands\r\nand test your skills @ Web Mania.\r\n</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>Team size is at most 3 members.</li>\r\n<li>The event will be conducted in two phases.</li>\r\n<li>Phase-1: The participants are required to mail a web-site prepared by them on the given topics only.</li>\r\n<li>Phase-2: It will be an on-campus round. The best 10 teams of Phase-1 have to prepare a website on the given case provided to them during Infotsav''12.</li>\r\n<li>Students pursuing graduation and post-graduation in any Indian university are eligible.</li>\r\n<li>Any team found having fake information regarding qualification criteria or profile information will be immediately disqualified.</li>\r\n<li>The participants are not allowed to use CMS such as Drupal or Joomla. </li>\r\n<li>The contestants are requested to strictly adhere to the deadlines. </li>\r\n<li>The decision of the judges and organizers will be final. No queries in this regard will be entertained.</li>\r\n<li>Evaluation Criteria:</li>\r\n&#160;<li>Design </li>\r\n&#160;<li>Content</li>\r\n&#160;<li>Innovation</li></ul>', '<ul><h5>Phase - 1:</h5> \r\n<li>Start of Round 1:                          24th September 2012</li>\r\n<li>Deadline for Submission:                   15th  October 2012</li>\r\n<li>Declaration of Results:                    20th  October 2012</li>\r\n\r\n<h5>Phase - 2: </h5>\r\n<li>Details will be uploaded soon.</li> </ul>', 3),
(22, 'witch_h', 'Witch Hunt', '<ul><li>Witch hunt, the debugging contest is not only about programming talent but also about applying the sheer knowledge to rectify errors.The challenge tests a programmer''s ability to understand and respond to dissimilar codes. The art of rectification / debugging is difficult than conventional programming because it''s not about what you know, it''s about how much you know and how you apply those cognitive ideas to recognize errors and act upon them. The event tests the programmer in areas of speed, intellect and understanding. A programmer stands nowhere if takes ages to understand and device an algorithm, hence it requires to comply!\r\nThe ability to perceive the programming style different from one''s own takes some doing and if you are up against the challenge, better get started by becoming a part of Witch Hunt.</li><li>Prize Money : Rs.6000</li></ul>', '<ul><li>Maximum Team size is 2.</li>\r\n<li> No late submissions will be entertained. (unless the time limit is extended).</li>\r\n<li>You aren''t allowed to skip a question and return to it later.</li>\r\n<li>The Event is divided in two Phases</li>\r\n     <li> Phase I - Preliminary Phase (Online)</li>\r\n      <li>Phase II - Main Phase ( At ABV-IIITM, Gwalior Campus) </li>\r\n<li>First Phase will consist of three levels:</li>\r\n&#160;<li>First level will consist of multiple choice questions (only one correct) with negative (-) marking. </li>\r\n&#160;<li>Second level will consist of multiple choice questions (one or more than one correct) with no negative (-) marking.</li>\r\n&#160;<li>Third level will consist of submit type questions with no negative (-) marking. </li>\r\n<li> Number of questions and duration will be disclosed at the time of contest.</li>\r\n<li>Any team which attempts to hack/deliberately crash the judging system will be immediately disqualified. </li>\r\n\r\n<li>The decision of the organizers in declaring the results will be final. No queries in this regard will be entertained.</li>\r\n</ul>', '<ul><li>Preliminary Round:	3rd Nov''12</li>\r\n<li>Result Declaration:	5th Nov''12</li>\r\n<li>Main Round:		10th Nov''12</li>\r\n</ul>', 4);

-- --------------------------------------------------------

--
-- Table structure for table `reg`
--

CREATE TABLE IF NOT EXISTS `reg` (
  `user_id` varchar(250) NOT NULL,
  `event_id` varchar(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `reg`
--

INSERT INTO `reg` (`user_id`, `event_id`) VALUES
('14', '3'),
('14', '9'),
('14', '2'),
('14', '10'),
('14', '4'),
('13', '2'),
('13', '8'),
('13', '3'),
('13', '10'),
('13', '15'),
('17', '5'),
('17', '8'),
('17', '11'),
('17', '16'),
('17', '22'),
('17', '3'),
('17', '12'),
('17', '17'),
('13', '5'),
('13', '1'),
('13', '4'),
('13', '6'),
('13', '7'),
('13', '9'),
('13', '11'),
('13', '12'),
('13', '13'),
('13', '14'),
('13', '16'),
('13', '17'),
('13', '18'),
('13', '19'),
('13', '20'),
('13', '21'),
('13', '22'),
('14', '5'),
('14', '13'),
('14', '14'),
('14', '18'),
('14', '19'),
('14', '7'),
('14', '8'),
('14', '11'),
('14', '12'),
('14', '20'),
('14', '21'),
('14', '22'),
('14', '1'),
('14', '6'),
('14', '15'),
('14', '16'),
('14', '17'),
('18', '3'),
('18', '4'),
('18', '9'),
('18', '10'),
('18', '1'),
('18', '2'),
('18', '5'),
('18', '6'),
('18', '7'),
('18', '8'),
('18', '11'),
('18', '12'),
('18', '13'),
('18', '14'),
('18', '15'),
('18', '16'),
('18', '17'),
('18', '18'),
('18', '19'),
('18', '20'),
('18', '21'),
('18', '22');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `id` int(250) NOT NULL AUTO_INCREMENT,
  `fname` text NOT NULL,
  `lname` text NOT NULL,
  `city` text NOT NULL,
  `sex` text NOT NULL,
  `mail` varchar(40) NOT NULL,
  `passw` varchar(200) NOT NULL,
  `mob` varchar(100) NOT NULL,
  `sq` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mail` (`mail`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=19 ;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `fname`, `lname`, `city`, `sex`, `mail`, `passw`, `mob`, `sq`) VALUES
(9, 'Aditya', 'Verma', 'sffdfs', 'male', 'fdsfs@gsg.ac.in', 'e10adc3949ba59abbe56e057f20f883e', '2147483647', 'sfddf'),
(11, 'Prateek', 'Jain', 'Indore', 'male', 'pratee@gg.com', 'e10adc3949ba59abbe56e057f20f883e', '7828212362', 'ssiufbuishiu'),
(12, 'afjal', 'afjal', '4654', 'male', 'yugagd@tt.om', 'db6141790d89c746affd3c95515d2574', '8984984923', 'afjal'),
(13, 'prateek', 'jain', 'jaifoa', 'male', 'prateekd2@gmail.com', 'e10adc3949ba59abbe56e057f20f883e', '7828212362', 'jiojoi'),
(14, 'Shree', 'Jai', 'kjhg', 'male', 'shr@yr.in', 'e10adc3949ba59abbe56e057f20f883e', '7845784596', 'ki'),
(17, 'Rahul', 'Jain', 'pune', 'male', 'rahul@gmail.com', '2acb7811397a5c3bea8cba57b0388b79', '7828212545', 'jay'),
(18, 'Sanjay', 'Jain', 'Meghnagar', 'male', 'sanjay@gmail.com', 'b51e8dbebd4ba8a8f342190a4b9f08d7', '9425102114', 'prateek');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
