<?php

/**
 * Implements hook_library().
 */
function yoxview_library() {
  // YoxView
  $path = drupal_get_path('module', 'yoxview');
  $libraries['yoxview'] = array(
    'title' => 'YoxView',
    'website' => 'http://www.yoxigen.com/yoxview/',
    'version' => '2.2',
    'js' => array(
      // The Drupal behavior.
      $path . '/yoxview.js' => array(),

      // YoxView itself.
      $path . '/yoxview/yox.js' => array(
        'weight' => JS_LIBRARY,
      ),
      $path . '/yoxview/jquery.yoxview-2.2.js' => array(
        'weight' => JS_LIBRARY + 1,
        'preprocess' => FALSE, // Can't be aggregated until the path can be set
      ),
    ),
    'css' => array(
      $path . '/yoxview/yoxview.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_field_formatter_info().
 */
function yoxview_field_formatter_info() {
  // The straight image with YoxView ontop of it.
  $formatters = array(
    'yoxview' => array(
      'label' => t('YoxView'),
      // Provides a display ontop of the image field.
      'field types' => array('image'),
      'settings' => array(
        // The Image Style that will provide the preview image.
        'image_style' => '',
      ),
    ),
  );

  return $formatters;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function yoxview_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  // Provide the image style.
  $image_styles = image_style_options(FALSE);
  $element['image_style'] = array(
    '#title' => t('Image style'),
    '#type' => 'select',
    '#default_value' => $settings['image_style'],
    '#empty_option' => t('None (original image)'),
    '#options' => $image_styles,
  );

  // @TODO: Provide some additional options as found from YoxView.
  // http://www.yoxigen.com/yoxview/usage.aspx#options

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function yoxview_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = array();

  $image_styles = image_style_options(FALSE);
  // Unset possible 'No defined styles' option.
  unset($image_styles['']);
  // Styles could be lost because of enabled/disabled modules that defines
  // their styles in code.
  if (isset($image_styles[$settings['image_style']])) {
    $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
  }
  else {
    $summary[] = t('Original image');
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function yoxview_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach ($items as $delta => $item) {
    // Render each image with a link to the original image.
    $element[$delta] = array(
      '#theme' => 'yoxview_image_formatter',
      '#item' => $item,
      '#path' => $item['uri'],
      '#alt' => $item['alt'],
      '#title' => $item['title'],
    );
    $element[$delta]['#attached']['library'][] = array('yoxview', 'yoxview');
    if (isset($display['settings']['image_style']) && !empty($display['settings']['image_style'])) {
      $element[$delta]['#style_name'] = $display['settings']['image_style'];
    }
  }

  return $element;
}

/**
 * Implements hook_theme().
 */
function yoxview_theme() {
  return array(
    'yoxview_image_formatter' => array(
      'variables' => array('item' => NULL, 'path' => NULL, 'alt' => NULL, 'title' => NULL, 'style_name' => NULL),
    ),
  );
}

/**
 * Returns HTML for the YoxView image formatter.
 *
 * @param $variables
 *   An associative array containing:
 *   - item: The array of element data.
 *   - path: The path of the image to use.
 *   - alt: The alt tag for the image.
 *   - title: The title tag for the image.
 *   - style_name: The name of the image style for the image tag.
 *
 * @ingroup themeable
 */
function theme_yoxview_image_formatter($variables) {
  // Render the image first.
  $output = '';
  if (isset($variables['style_name']) && !empty($variables['style_name'])) {
    $output = theme('image_style', $variables);
  }
  else {
    $output = theme('image', $variables);
  }

  // Wrap it in a link.
  $path = file_create_url($variables['path']);
  $output = l($output, $path, array(
    'html' => TRUE,
    'attributes' => array( 
      'class' => array('yoxview_thumbnail'),
    ),
  ));
  return $output;
}

